### ISSUE TITLE
Missing Find-Events & Chart

### ISSUE THREAD

**Issue by AlexYoung28** [EvotecIT/Dashimo#4]
Find-Events : The term 'Find-Events' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:9 char:22
+     $DataSetEvents = Find-Events -Report UserChangesDetailed, UserCha ...
+                      ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Find-Events:String) [], Command 
   NotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Chart : The term 'Chart' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At line:83 char:21
+                     Chart -DataTable $DataSetForest.FoundDomains.'den ...
+                     ~~~~~
    + CategoryInfo          : ObjectNotFound: (Chart:String) [], CommandNotFou 
   ndException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by PrzemyslawKlys** [comment]
Right, find-events is part of [PSWinReporting](https://evotec.xyz/hub/scripts/pswinreporting-powershell-module/) but only in the newest 2.0 version https://evotec.xyz/pswinreporting-1-8-split-of-branches-legacy-vs-new-hope/ 

```
Install-Module PSWinReporting -AllowPrerelease -Force
```

As for charts, I've temporary removed charts because those were not working the way I wanted. They will come back but it will take a moment.
